### ISSUE TITLE
Window title area extends over boxy-style controls

### ISSUE THREAD

**Issue by b3u** [carbon-app/carbon#1033] opened 2020-06-15 13:24 UTC
**Describe the bug**
When using the boxy window controls, the image title text-area extends over the controls. This is hard to read, and doesn't look nice.

**To Reproduce**
1. In settings, change the window controls type to the last option (boxy).
2. Click towards the top of the window in the image.
3. Type, and watch the text run into the window controls.

**Expected behavior**

**Screenshots**
![carbon](https://user-images.githubusercontent.com/39805353/84662476-d7d69a00-aee9-11ea-9e67-d48e4fc09578.png)

**Info (please complete the following information):**
- OS [e.g. macOS, Linux, Windows, iOS]: Linux (xubuntu 20.04)
- Browser [e.g. chrome, safari]: chrome 83

**Comment by mfix22** [comment] 2020-06-16 03:28
@b3u would widening the container a bit  work for you? 
![carbon (1)](https://user-images.githubusercontent.com/8397708/84728661-91fbef00-af46-11ea-8d39-eb5d0e1ad2fa.png)

You can do this by dragging the right edge of the Carbon container.

**Comment by b3u** [comment] 2020-06-16 14:34
> @b3u would widening the container a bit work for you?

I think that's a great temporary fix. By the way, the carbon container never lets go of my cursor. I have a gif of it. I'll open a new issue.

I was playing around with the styles. Adding a max-width to the input should eliminate the issue completely. If 54px is the set size of the window controls svg, then the input should have a max-width of `calc(100% - 54px)`.

```css
input {
    max-width: calc(100% - 54px);
}
```

**Comment by mfix22** [comment] 2020-06-17 02:16
@b3u feel free to open a PR with this change. If it's simple, and doesn't break existing styles, I'll probably merge it 🙂

**Comment by b3u** [comment] 2020-06-17 16:17
@mfix22 I noticed that the contributing guidelines is doesn't show the complete command for adding a contribution. It says `yarn contrib:add <your GitHub username>` instead of `yarn contrib:add <your GitHub username> <contribution>`. Would you like me to open a new issue?

**Comment by mfix22** [comment] 2020-06-18 03:26
I added it 👍 

No need to open a new issue for a change as small as that one, you can just open a PR for consideration instead.

**Comment by mfix22** [comment] 2020-06-19 02:14
@faraz16iqbal there have already been 2 PRs submitted for it, but they have not yet merged, so the issue is still open.

**Closed** 2020-06-19 02:22 UTC
Labels: help wanted
