### ISSUE TITLE
SVG titlebar is not in correct place!

### ISSUE THREAD

**Issue by Snuggle** [carbon-app/carbon#1099] opened 2020-09-14 13:46 UTC
I believe this issue may have been introduced by issue  #1095.

The MacOS style buttons are not a part of the window and are just floating off into space.

**Carbon Preview**
![image](https://user-images.githubusercontent.com/26250962/93093544-b75cde00-f698-11ea-89fb-5826477deec5.png)

**Exported SVG**
![image](https://user-images.githubusercontent.com/26250962/93093513-af04a300-f698-11ea-852f-e243af9c54f3.png)

# Attached Broken SVG
[BrokenTitleBarSVG.zip](https://github.com/carbon-app/carbon/files/5218809/BrokenTitleBarSVG.zip)

**Comment by mfix22** [comment] 2020-09-17 01:14
@Snuggle can you please post a link to the Carbon snippet that recreates the issue, as it states in the Issue Template? 🙂

**Comment by mfix22** [comment] 2020-09-17 01:16
Also, could you include which operating system and browser you are using?

**Comment by mfix22** [comment] 2020-09-17 01:42
@qw-in do you know if the % in the `<foreignObject x="0" y="0" width="100%" height="100%">` should be replaced as well? Could that be causing this issue? 

(really appreciate your help with this in advance)

**Comment by Snuggle** [comment] 2020-09-30 12:24
# Additional Details
Here you go, @mfix22!
## Code Snippet
```
<div class="displayInline">
    <span>I'm made up of two</span> <span>inline elements!</span>
</div>
```

## Carbon URL
https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=theme%3A4yomt37mq1&wt=none&l=htmlmixed&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=%253Cdiv%2520class%253D%2522displayInline%2522%253E%250A%253Cspan%253EI%27m%2520made%2520up%2520of%2520two%253C%252Fspan%253E%2520%253Cspan%253Einline%2520elements!%253C%252Fspan%253E%250A%253C%252Fdiv%253E

## Operating System
Reproducible on Linux, macOS and Windows

## Browser
Tested in Firefox 81.0 (64-bit) and Vivaldi (Unknown version)

**Comment by Snuggle** [comment] 2020-09-30 12:24
The issue does still not seem to have been fixed, either!

**Comment by mfix22** [comment] 2020-10-03 17:47
Hi @Snuggle, 
I just followed that link, downloaded it as an SVG, and got this as a resulting image:

<img width="1280" alt="Screen Shot 2020-10-03 at 10 46 00 AM" src="https://user-images.githubusercontent.com/8397708/94998296-b5828e00-0565-11eb-8a1c-f3cb98127d58.png">

Would you be able to provide more detailed steps to reproduce the issue you are noticing?

**Comment by Snuggle** [comment] 2020-10-03 18:30
@mfix22 Hmm. Interesting, perhaps it's being caused by the theme?

I'll try to investigate when I can!

**Comment by mfix22** [comment] 2020-10-03 19:43
Thanks @Snuggle! No rush, really appreciate your help here 🙂

**Comment by Snuggle** [comment] 2020-10-09 09:38
Hmm. After further testing, I can only reproduce this again using a Chromium based browser such as Vivaldi or MS Edge, it doesn't seem to happen with Firefox anymore. (Though I am almost certain I had this issue there?)

### Here's exactly what I had did to reproduce:
1) Open Microsoft Edge or Vivaldi in a private tab (I'm assuming any Chromium-based browser has this issue)
2) Only using the defaults provided by https://carbon.now.sh, theme should be `Seti`, syntax should be `Auto`, background should be grey `ABB8C3`.
![image](https://user-images.githubusercontent.com/26250962/95567620-1c4af000-0a1b-11eb-8c5c-222ab8633cde.png)
3) Click on the `v` arrow to the right of 'Export' and then as an SVG (x2)
![image](https://user-images.githubusercontent.com/26250962/95567655-2b31a280-0a1b-11eb-9e35-57dcb3fddb32.png)
4) Open the downloaded SVG with a Chromium based browser such as Vivaldi or MS Edge

**Comment by Snuggle** [comment] 2020-10-09 09:53
[Please open SVG with Chromium.zip](https://github.com/carbon-app/carbon/files/5354027/Please.open.SVG.with.Chromium.zip)

**Comment by mfix22** [comment] 2020-10-27 01:46
@Snuggle this seems like it might be a Browser specific issue, one that Carbon doesn't have much say in it getting fixed 😅 

If you want, you could open an issue in a browser issue queue, but I'm not sure how they would prioritize this either (since it is an issue _between_ browsers)

All this said, please don't take offense to me closing this issue. I really appreciate you digging into all this, but as long as it is working fine in individual browsers, that is as much as we can ask for 🙂

**Closed by mfix22** 2020-10-27 01:46 UTC
Labels: Hacktoberfest
