### ISSUE TITLE
Edit custom theme

### ISSUE THREAD

**Issue by Spielboerg** [carbon-app/carbon#1105] opened 2020-09-28 14:15 UTC
As the title says, it would be great to be able to edit ~or delete~ the custom themes.

I saw that the custom themes are stored in local storage and I could change it there as a workaround. However, I'm using the Carbonize app (https://www.dangercove.com/carbonize/) in which I don't have access to the local storage.

Edit:
I found the delete option: the theme must not be selected, and then there is a very small X to delete the theme. I think it would be better if the X was bigger.

Unfortunately, the option "Export config" in the settings does not include the custom themes. Maybe an "export/import themes" option would be a simple and fast quick fix?

**Comment by mfix22** [comment] 2020-10-03 17:54
@Spielboerg totally! This is actually an existing issue that I am definitely eager to investigate (https://github.com/carbon-app/carbon/issues/1063)

You are totally that the "X" probably could be bigger for this feature. I will look into fixing that immediately. 

Regarding Carbonize, we don't consider that app a supported part of the Carbon ecosystem. If you are interesting in using Carbon as a Desktop app, you should use our fully supported PWA, which you can install by following the instructions in the README (https://github.com/carbon-app/carbon#installing-carbon-for-desktop-offline). Our desktop app can even be used when offline (great for plane rides ✈️)

I'm going to mark this issue as a duplicate of #1063, but I'm not going to close it until I fix the "X" buttons

**Closed** 2020-10-03 19:31 UTC
Labels: enhancement
