### ISSUE TITLE
The exported svg file can not be open in svg edit appilications

### ISSUE THREAD

**Issue by zhqu1148980644** [carbon-app/carbon#1182] opened 2021-03-03 02:58 UTC
**Describe the bug**
The exported svg file can not be correctly opened in svg edit applications like `Inkscape`.

**To Reproduce**
1. export any python code to svg file.
2. open in Inkscape(macos verions)
3. Only blank shown in the application.

**Expected behavior**

show the svg correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/29366130/109745591-15618b80-7c0f-11eb-866d-ea010a7116c7.png)

**Info (please complete the following information):**

- OS [macOS]
- Browser [Chrome]
- Carbon URL [https://carbon.now.sh/e4jspc4CJPNG5RkmMewt]

<details>
  <summary>Code snippet</summary>
  <pre>a = 1</pre>
</details>

**Comment by adghayes** [comment] 2021-03-04 21:56
Duplicate of #496

**Comment by mfix22** [comment] 2021-03-07 01:21
^ @adghayes is right here. We will track this issue over at #496. If you have suggestions for replacing the `foreignObject` implementation, please let us know.

**Closed by mfix22** 2021-03-07 01:21 UTC
Labels: bug
