### ISSUE TITLE
Pressing “Space” does nothing

### ISSUE THREAD

**Issue by VladimirCreator** [carbon-app/carbon#1212] opened 2021-04-24 13:59 UTC
**Describe the bug**
The problem with typing code. If you try to press “Space” then happens nothing.

**To Reproduce**

1. Tap anywhere in code editor
2. Press "Space"
3. See nothing happened

**Expected behavior**
There should appear a character ' '.

**Screenshots**
There are not screenshots.

**Info:**

- OS: iPadOS 14.4.2
- Browser: Safari
- Carbon URL: https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=seti&wt=none&l=auto&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=true&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=true&code=funcbubblesort

**Comment by thakreyn** [comment] 2021-05-20 07:54
> **Describe the bug**
> The problem with typing code. If you try to press “Space” then happens nothing.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Tap anywhere in code editor
> 2. Press "Space"
> 3. See nothing happened
> 
> **Expected behavior**
> There should appear a character ' '.
> 
> **Screenshots**
> There are not screenshots.
> 
> **Info:**
> 
> * OS: iPadOS 14.4.2
> * Browser: Safari
> * Carbon URL: https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=seti&wt=none&l=auto&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=true&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=true&code=funcbubblesort

@VladimirCreator, I guess the bug has either been fixed or there was an issue on your personal device. Because on reproducing the mentioned conditions, the 'space' worked fine and added the ' ' character.

**Comment by mfix22** [comment] 2021-05-22 21:28
Has anyone else been able to reproduce this? I have tested it on an iPad emulator, and it seems to function fine for me. 

@VladimirCreator is this issue persisting?

**Comment by VladimirCreator** [comment] 2021-05-23 05:00
@mfix22 Yes. Here is [a video](https://user-images.githubusercontent.com/49140851/119248879-8af54c00-bbad-11eb-9808-087b586b787d.MOV) that demonstrates the bug.

**Comment by mfix22** [comment] 2021-08-21 18:23
@VladimirCreator — is this the issue you are noticing: https://github.com/codemirror/CodeMirror/issues/3403?

**Comment by VladimirCreator** [comment] 2021-08-21 18:50
@mfix22 No.

**Comment by sukima** [comment] 2021-09-23 01:28
Yes I can confirm. On iPad (10 inch) in landscape orientation if I type `const foo` the result is `constfoo` and the screen attempts to _scroll_ during the press of the <kbd>space</kbd> button.

I think this is a case that if the viewport feels the need to scroll that the <kbd>space</kbd> causes a scroll-down event and the editor never gets the keyboard event.

**Comment by rkoleci** [comment] 2021-12-06 13:06
Can you assign this to me ?

**Comment by mfix22** [comment] 2022-01-25 04:20
> Can you assign this to me ?

@rkoleci done!

**Comment by mfix22** [comment] 2022-04-03 02:32
@rkoleci do you have any updates here? Have you been able to reproduce the issue?

**Comment by mfix22** [comment] 2022-05-16 00:30
Closing as out-of-date. Please open a new issue if this persists.

**Closed by mfix22** 2022-05-16 00:30 UTC
Labels: bug, help wanted, bug:needs-reproduction
