### ISSUE TITLE
Sign Up with GitHub Not Working

### ISSUE THREAD

**Issue by Joshmatjjen** [carbon-app/carbon#1059] opened 2020-07-29 20:58 UTC
### Expected Behavior

If applicable, add screenshots to help explain your problem, or include Carbon links that recreate
your issue.

### Info

Please complete the following information:

OS [e.g. macOS, Linux, Windows, iOS]:

Browser [e.g. Chrome, Safari, Firefox]:

**Comment by mfix22** [comment] 2020-07-30 01:58
@Joshmatjjen could you give me more information on the issue you are seeing? Which browser/operating system were you using? Can you provide a screenshot or screen recording of the issue you are noticing?

**Comment by mfix22** [comment] 2020-07-30 02:29
Actually, just realized this is a duplicate of #1058. Will close this one and continue the thread there.

**Closed by mfix22** 2020-07-30 02:29 UTC
