### ISSUE TITLE
Overlapping lines when exporting PNG

### ISSUE THREAD

**Issue by maxjf1** [carbon-app/carbon#903] opened 2019-10-31 04:29 UTC
### Expected Behavior
![image](https://user-images.githubusercontent.com/6114888/67919052-96bd8f80-fb7d-11e9-8f08-6d03fcde2c93.png)

### Actual Behavior
![carbon](https://user-images.githubusercontent.com/6114888/67919018-7beb1b00-fb7d-11e9-85b2-fa489da9f5a2.png)

<details>
  <summary>Browser:  Chrome</summary>
</details>

<details>
  <summary>Code Snippet </summary>
# Executa a busca usando a abordagens diversas de calculos de custo
def perform_search(self, calculate_cost_function=None):
    closed_states = list()
    tree = PG.AGraph(directed=True, strict=True)
    states = [self.root]
    while len(states) > 0:
        current_state = states.pop()
        if current_state in closed_states or current_state in current_state.path:
          continue
        tree.add_node(current_state.id, label=str(current_state.value))
        if len(current_state.path) > 0:
            tree.add_edge(current_state.path[0].id, current_state.id)
        if current_state.is_final():
            return current_state, tree
        children = self.problem.move(current_state, calculate_cost_function)
        states += children
        closed_states.append(current_state)
        if calculate_cost_function:
            states.sort()
    return None, tree

</details>
happened when i exported PNG

<details>
  <summary>Carbon config</summary>
{"paddingVertical":"0px","paddingHorizontal":"0px","backgroundImage":null,"backgroundImageSelection":null,"backgroundMode":"color","backgroundColor":"rgba(255,255,255,1)","dropShadow":false,"dropShadowOffsetY":"20px","dropShadowBlurRadius":"68px","theme":"one-light","windowTheme":"bw","language":"auto","fontFamily":"Hack","fontSize":"14px","lineHeight":"143%","windowControls":false,"widthAdjustment":false,"lineNumbers":false,"firstLineNumber":1,"exportSize":"2x","watermark":false,"squaredImage":false,"hiddenCharacters":false,"loading":false,"icon":"&#x2F;static&#x2F;presets&#x2F;1.png","isVisible":true}
</details>

**Comment by maxjf1** [comment] 2019-10-31 04:31
Also Happens with SVG

**Comment by mfix22** [comment] 2019-10-31 20:51
@maxjf1 which browser and OS did you experience this on? I am assuming this is a duplicate of #743

**Comment by maxjf1** [comment] 2019-10-31 23:29
> @maxjf1 which browser and OS did you experience this on? I am assuming this is a duplicate of #743

Chrome in Linux (Deepin, Debian)

**Comment by mfix22** [comment] 2019-11-02 01:20
Closing as duplicate of #743 — would greatly appreciate your helping looking into that issue 🙏

**Closed by mfix22** 2019-11-02 01:20 UTC
