### ISSUE TITLE
SVG export fails to open in system image viewer

### ISSUE THREAD

**Issue by Ajith-stark** [carbon-app/carbon#1162] opened 2021-01-20 10:12 UTC
**Describe the bug**
Exporting code into SVG is not working as expected. It exports data (xml data) but fails to render image all I can see is alpha channel (transparent background). 
Opening it in editor shows some boilderplate code thats it no code that represents my input text.
I am not sure why it exactly happening but seems "foreignObject" is problem.

**To Reproduce**
1. Visit site.
2. type some code or leave default auto-gen code.
3. click export & select it as svg.

**Expected behavior**
you know

**Screenshots**
![image](https://user-images.githubusercontent.com/47944176/105159673-5ad16a00-5b35-11eb-8618-2d3f830e1cf2.png)
![image](https://user-images.githubusercontent.com/47944176/105160242-024e9c80-5b36-11eb-83da-902b5e5b5523.png)

**Info (please complete the following information):**

- Linux 5.4.0-62-generic #70~18.04.1-Ubuntu  x86_64  GNU/Linux
- FIrefox 84.0.2 (64-bit

**Comment by mfix22** [comment] 2021-01-21 03:05
Can you share a Carbon link that reproduces this issue? 

I expect this to be a duplicate of #943

**Comment by Ajith-stark** [comment] 2021-01-21 13:07
Hey turns out my system image viewer (GNOME image viewer /Eye of GNOME) on Ubuntu fails to load image, 
I tried opening different SVG file & it renders image as expected.
Also opening SVG file in inkscape shows only white background (I wanted to export it as pdf ).
code link ; https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=blackboard&wt=none&l=text%2Fx-csrc&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=4x&wm=false.

**Comment by mfix22** [comment] 2021-01-24 01:33
Makes sense! This is indeed a duplicate of #943. Certain applications don't know how to render a foreignObject correctly, and it can lead to visual glitches like this. At the moment, we don't know a way around this problem.

We are tracking this issue over in #943, so I'm going to close this.

**Closed by mfix22** 2021-01-24 01:33 UTC
Labels: bug, help wanted
