### ISSUE TITLE
Javascript promise errors in console

### ISSUE THREAD

**Issue by esimov** [carbon-app/carbon#927] opened 2020-01-09 08:04 UTC
I'm getting a lot of Javascript `Promise` errors in the console like the one in the screenshot below. The code snippets are showing correctly, but still the console log errors are annoying. 

![image](https://user-images.githubusercontent.com/883386/72049317-58ec8e00-32c7-11ea-8324-5c909e5b6ab0.png)

**Comment by mfix22** [comment] 2020-01-10 18:03
@esimov can you post a Snippet or Carbon URL that I can try testing on to debug the issue?

**Comment by esimov** [comment] 2020-01-12 13:45
Sure, here it is:

https://carbon.now.sh/embed?bg=rgba(187%2C187%2C187%2C0)&t=seti&wt=sharp&l=text%2Fx-go&ds=true&dsyoff=3px&dsblur=13px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=%252F%252F%2520Render%2520calls%2520the%2520%2560requestAnimationFrame%2560%2520Javascript%2520function%2520in%2520asynchronous%2520mode.%250Afunc%2520(c%2520*Canvas)%2520Render()%2520%257B%250A%2509var%2520data%2520%253D%2520make(%255B%255Dbyte%252C%2520c.windowSize.width*c.windowSize.height*4)%250A%2509c.done%2520%253D%2520make(chan%2520struct%257B%257D)%250A%250A%2509if%2520err%2520%253A%253D%2520det.UnpackCascades()%253B%2520err%2520%253D%253D%2520nil%2520%257B%250A%2509%2509c.renderer%2520%253D%2520js.FuncOf(func(this%2520js.Value%252C%2520args%2520%255B%255Djs.Value)%2520interface%257B%257D%2520%257B%250A%2509%2509%2509go%2520func()%2520%257B%250A%2509%2509%2509%2509c.window.Get(%2522stats%2522).Call(%2522begin%2522)%250A%250A%2509%2509%2509%2509width%252C%2520height%2520%253A%253D%2520c.windowSize.width%252C%2520c.windowSize.height%250A%2509%2509%2509%2509c.reqID%2520%253D%2520c.window.Call(%2522requestAnimationFrame%2522%252C%2520c.renderer)%250A%2509%2509%2509%2509%252F%252F%2520Draw%2520the%2520webcam%2520frame%2520to%2520the%2520canvas%2520element%250A%2509%2509%2509%2509c.ctx.Call(%2522drawImage%2522%252C%2520c.video%252C%25200%252C%25200)%250A%2509%2509%2509%2509rgba%2520%253A%253D%2520c.ctx.Call(%2522getImageData%2522%252C%25200%252C%25200%252C%2520width%252C%2520height).Get(%2522data%2522)%250A%250A%2509%2509%2509%2509uint8Arr%2520%253A%253D%2520js.Global().Get(%2522Uint8Array%2522).New(rgba)%250A%2509%2509%2509%2509js.CopyBytesToGo(data%252C%2520uint8Arr)%250A%2509%2509%2509%2509pixels%2520%253A%253D%2520c.rgbaToGrayscale(data)%250A%2509%2509%2509%2509res%2520%253A%253D%2520det.DetectFaces(pixels%252C%2520height%252C%2520width)%250A%2509%2509%2509%2509c.drawDetection(res)%250A%250A%2509%2509%2509%2509c.window.Get(%2522stats%2522).Call(%2522end%2522)%250A%2509%2509%2509%257D()%250A%2509%2509%2509return%2520nil%250A%2509%2509%257D)%250A%2509%2509c.window.Call(%2522requestAnimationFrame%2522%252C%2520c.renderer)%250A%2509%2509c.detectKeyPress()%250A%2509%2509%253C-c.done%250A%2509%257D%250A%257D

This is the url where i'm getting the errors: https://esimov.com/2020/01/pigo-wasm

**Comment by mfix22** [comment] 2020-01-13 00:56
I am fairly sure this was caused by the same issue as: https://github.com/carbon-app/carbon/issues/929

I think the link you posted is a broken link. Can you try posting a new one?

**Comment by esimov** [comment] 2020-01-13 06:13
I'm posting a new one:

https://carbon.now.sh/embed?bg=rgba(187%2C187%2C187%2C0)&t=seti&wt=sharp&l=text%2Fx-go&ds=true&dsyoff=3px&dsblur=13px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=%252F%252F%2520FetchCascade%2520retrive%2520the%2520cascade%2520file%2520trough%2520a%2520JS%2520http%2520connection.%250A%252F%252F%2520It%2520should%2520return%2520the%2520binary%2520data%2520as%2520uint8%2520integers%2520or%2520err%2520in%2520case%2520of%2520an%2520error.%250Afunc%2520(d%2520*Detector)%2520FetchCascade(url%2520string)%2520(%255B%255Dbyte%252C%2520error)%2520%257B%250A%2509d.respChan%2520%253D%2520make(chan%2520%255B%255Duint8)%250A%2509d.errChan%2520%253D%2520make(chan%2520error)%250A%250A%2509promise%2520%253A%253D%2520js.Global().Call(%2522fetch%2522%252C%2520url)%250A%2509success%2520%253A%253D%2520js.FuncOf(func(this%2520js.Value%252C%2520args%2520%255B%255Djs.Value)%2520interface%257B%257D%2520%257B%250A%2509%2509response%2520%253A%253D%2520args%255B0%255D%250A%2509%2509response.Call(%2522arrayBuffer%2522).Call(%2522then%2522%252C%2520js.FuncOf(func(this%2520js.Value%252C%2520args%2520%255B%255Djs.Value)%2520interface%257B%257D%2520%257B%250A%2509%2509%2509go%2520func()%2520%257B%250A%2509%2509%2509%2509buffer%2520%253A%253D%2520args%255B0%255D%250A%2509%2509%2509%2509uint8Array%2520%253A%253D%2520js.Global().Get(%2522Uint8Array%2522).New(buffer)%250A%250A%2509%2509%2509%2509jsbuf%2520%253A%253D%2520make(%255B%255Dbyte%252C%2520uint8Array.Get(%2522length%2522).Int())%250A%2509%2509%2509%2509js.CopyBytesToGo(jsbuf%252C%2520uint8Array)%250A%2509%2509%2509%2509d.respChan%2520%253C-%2520jsbuf%250A%2509%2509%2509%257D()%250A%2509%2509%2509return%2520nil%250A%2509%2509%257D))%250A%2509%2509return%2520nil%250A%2509%257D)%250A%250A%2509failure%2520%253A%253D%2520js.FuncOf(func(this%2520js.Value%252C%2520args%2520%255B%255Djs.Value)%2520interface%257B%257D%2520%257B%250A%2509%2509go%2520func()%2520%257B%250A%2509%2509%2509err%2520%253A%253D%2520fmt.Errorf(%2522unable%2520to%2520fetch%2520the%2520cascade%2520file%253A%2520%2525s%2522%252C%2520args%255B0%255D.String())%250A%2509%2509%2509d.errChan%2520%253C-%2520err%250A%2509%2509%257D()%250A%2509%2509return%2520nil%250A%2509%257D)%250A%250A%2509promise.Call(%2522then%2522%252C%2520success%252C%2520failure)%250A%250A%2509select%2520%257B%250A%2509case%2520resp%2520%253A%253D%2520%253C-d.respChan%253A%250A%2509%2509return%2520resp%252C%2520nil%250A%2509case%2520err%2520%253A%253D%2520%253C-d.errChan%253A%250A%2509%2509return%2520nil%252C%2520err%250A%2509%257D%250A%257D

**Comment by esimov** [comment] 2020-01-13 09:36
BTW something has broken in the meantime because some of the snippets from the link provided above are not working anymore, and i'm pretty sure that they have worked at the time when it has been posted. For example [this](https://carbon.now.sh/embed?bg=rgba(187%2C187%2C187%2C0)&t=seti&wt=sharp&l=javascript&ds=true&dsyoff=3px&dsblur=13px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=uint8Arr%2520%253A%253D%2520js.Global().Get(%2522Uint8Array%2522).New(rgba)) snippet is not working anymore:

But it worked last week. You can see that on [this](https://www.esimov.com/2020/01/pigo-wasm) page there are many empty (missing) spaces where the code should be.

**Comment by esimov** [comment] 2020-01-14 08:31
@mfix22 do you have any update regarding this issue? For example I simply could not export this code snippet as an iframe, because it gives me the following error:

```javascript
function fetchAndInstantiate(url, importObject) {
    return fetch(url).then(response =>
        response.arrayBuffer()
    ).then(bytes =>
        WebAssembly.instantiate(bytes, importObject)
    ).then(results =>
        results.instance
    );
}
var go = new Go();
var mod = fetchAndInstantiate("lib.wasm", go.importObject);
window.onload = function () {
    mod.then(function (instance) {
        go.run(instance);
    });
};
```
and the result is an empty page:

![image](https://user-images.githubusercontent.com/883386/72327042-017c6280-36b9-11ea-85eb-6f72cea9c905.png)

**Comment by mfix22** [comment] 2020-01-16 05:39
@Timer have you seen this issue? This seems to be related to #929

**Comment by Timer** [comment] 2020-01-16 15:23
It's likely related. I'd like to know the exact char causing this.

Looks like https://carbon.now.sh/embed?bg=rgba(187%2C187%2C187%2C0)&t=seti&wt=sharp&l=javascript&ds=true&dsyoff=3px&dsblur=13px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=uint8Arr%2520%253A%253D%2520js.Global().Get(%2522Uint8Array%2522).New(rgba) is the repo.

**Comment by esimov** [comment] 2020-01-18 05:45
Guys nu rush but did you found any resolution for this issue?

**Comment by mfix22** [comment] 2020-01-20 21:57
@timer this is a valid recreation: https://carbon.now.sh/embed?l=javascript

Could it be because of the javascript keyword?

**Comment by mfix22** [comment] 2020-01-20 22:04
I just looked into this _super_ briefly, but this may have been the cause of the issues: https://github.com/GoogleChromeLabs/native-url/blob/master/src/parse.js#L52

**Comment by Timer** [comment] 2020-01-20 23:56
@mfix22 this is fixed in the latest `next@canary`. Please upgrade!

**Closed** 2020-01-23 02:05 UTC

**Comment by esimov** [comment] 2020-01-23 05:51
Thanks a lot!
