### ISSUE TITLE
Line-wrapping bug

### ISSUE THREAD

**Issue by jsejcksn** [carbon-app/carbon#781] opened 2019-06-08 23:20 UTC
Potentially related to #761

### Expected Behavior

  - Code is not line-wrapped, OR
  - code is line-wrapped at 80 chars and preserves indentation, OR
  - control over line-wrapping (best behavior)

### Actual Behavior

Line with <= 80 chars gets wrapped to newline, ignoring indentation

(Compare lines 5 and 6 in the output below to the input snippet)

#### Output:

![3cf10212-a156-4cde-9756-e245851c5b51](https://user-images.githubusercontent.com/868251/59153187-52d4bd00-8a19-11e9-87bf-6fb9f9ba5c97.png)

#### Input:

```js
function html (tagName, attributes, ...childNodes) {
  const el = document.createElement(tagName);
  if (attributes) {
    for (const [prop, value] of Object.entries(attributes)) {
      if (prop === 'style' && (Array.isArray(value) || value instanceof Map)) {
        for (const declaration of value) {
          el.style.setProperty(...declaration);
        }
      }
      else {
        el.setAttribute(prop, value);
      }
    }
  }
  if (childNodes) {
    for (let node of childNodes) {
      if (typeof node === 'string') {
        node = document.createTextNode(node);
      }
      el.appendChild(node);
    }
  }
  return el;
}
```

#### Carbon config:

(Note: I removed the `icon` property)

```json
{
  "paddingVertical": "0px",
  "paddingHorizontal": "0px",
  "marginVertical": "45px",
  "marginHorizontal": "45px",
  "backgroundImage": null,
  "backgroundImageSelection": null,
  "backgroundMode": "color",
  "backgroundColor": "rgba(171, 184, 195, 1)",
  "dropShadow": false,
  "dropShadowOffsetY": "20px",
  "dropShadowBlurRadius": "68px",
  "theme": "one-dark",
  "windowTheme": "sharp",
  "language": "javascript",
  "fontFamily": "Hack",
  "fontSize": "14px",
  "lineHeight": "133%",
  "windowControls": false,
  "widthAdjustment": false,
  "lineNumbers": true,
  "exportSize": "2x",
  "watermark": false,
  "squaredImage": false,
  "loading": false,
  "isVisible": true,
  "custom": true
}
```

<details>
  <summary>Browser: </summary>
  Win 10, Chrome 75.0.3770.80
</details>

**Comment by mfix22** [comment] 2019-06-18 19:28
Hey @jsejcksn are you still noticing this issue? When I tested on current Carbon, I wasn't seeing the line-wrapping issue you were:

([Source](http://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=seti&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=function%2520html%2520(tagName%252C%2520attributes%252C%2520...childNodes)%2520%257B%250A%2520%2520const%2520el%2520%253D%2520document.createElement(tagName)%253B%250A%2520%2520if%2520(attributes)%2520%257B%250A%2520%2520%2520%2520for%2520(const%2520%255Bprop%252C%2520value%255D%2520of%2520Object.entries(attributes))%2520%257B%250A%2520%2520%2520%2520%2520%2520if%2520(prop%2520%253D%253D%253D%2520%27style%27%2520%2526%2526%2520(Array.isArray(value)%2520%257C%257C%2520value%2520instanceof%2520Map))%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520for%2520(const%2520declaration%2520of%2520value)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520el.style.setProperty(...declaration)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520el.setAttribute(prop%252C%2520value)%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%2520%2520%257D%250A%2520%2520if%2520(childNodes)%2520%257B%250A%2520%2520%2520%2520for%2520(let%2520node%2520of%2520childNodes)%2520%257B%250A%2520%2520%2520%2520%2520%2520if%2520(typeof%2520node%2520%253D%253D%253D%2520%27string%27)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520node%2520%253D%2520document.createTextNode(node)%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520el.appendChild(node)%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%257D%250A%2520%2520return%2520el%253B%250A%257D
))
![carbon](https://user-images.githubusercontent.com/8397708/59713436-55c37080-91c4-11e9-9ea2-c45c66830763.png)

**Comment by mfix22** [comment] 2019-06-18 19:48
(Also posting this for future reference for myself: https://codemirror.net/demo/indentwrap.html#)

**Comment by jsejcksn** [comment] 2019-06-19 01:12
LGTM on macOS; will check Windows env in the next day or so

**Comment by jsejcksn** [comment] 2019-06-19 05:16
Just checked on Windows: **Issue persists.**

_Win 10, Chrome 75.0.3770.100_

**Comment by jsejcksn** [comment] 2019-06-19 07:09
@mfix22 Are you testing in the same environment? (Win 10, Chrome stable)

**Comment by mfix22** [comment] 2019-08-19 05:46
Sorry, totally missed these comments. I was testing this on macOS.

**Comment by oliversturm** [comment] 2019-09-11 14:39
I stumbled into this issue and I can reproduce it in Linux Chromium (well, technically Brave - version shows `Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)`).

[Load this URL for my test case](https://carbon.now.sh/?bg=rgba(222%2C171%2C99%2C1)&t=duotone-dark&wt=none&l=graphql&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=false&pv=52px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=type%2520Country%2520%257B%250A%2520%2520name%253A%2520String!%250A%2520%2520areaKM2%253A%2520Int!%250A%2520%2520population%253A%2520Int!%250A%2520%2520areaPerPerson%253A%2520Float!%250A%257D%250A%250Atype%2520Query%2520%257B%250A%2520%2520countries(searchNames%253A%2520%255BString!%255D)%253A%2520%255BCountry!%255D!%250A%257D)

Using Export/Open gives me this image:

![image](https://user-images.githubusercontent.com/4730969/64706097-e13d5c80-d4a8-11e9-9ed6-a9d43739f681.png)

Now change the option "auto-adjust width" (switch it ON). Now Export/Open gives me this:

![image](https://user-images.githubusercontent.com/4730969/64706183-03cf7580-d4a9-11e9-9966-4422dccce3a9.png)

The second from last line has been wrapped and overlaps with the last line.

Now change the font size - for easy access, [here's the URL for the changed config](https://carbon.now.sh/?bg=rgba(222%2C171%2C99%2C1)&t=duotone-dark&wt=none&l=graphql&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=52px&ph=56px&ln=false&fl=1&fm=Hack&fs=12.5px&lh=133%25&si=false&es=2x&wm=false&code=type%2520Country%2520%257B%250A%2520%2520name%253A%2520String!%250A%2520%2520areaKM2%253A%2520Int!%250A%2520%2520population%253A%2520Int!%250A%2520%2520areaPerPerson%253A%2520Float!%250A%257D%250A%250Atype%2520Query%2520%257B%250A%2520%2520countries(searchNames%253A%2520%255BString!%255D)%253A%2520%255BCountry!%255D!%250A%257D). The font size is now set to 12.5px.

Export/Open renders this:

![image](https://user-images.githubusercontent.com/4730969/64706810-ff578c80-d4a9-11e9-9947-5cdbbd159d39.png)

Obviously, there is something going wrong in edge case scenarios when 

* a line is longer than a certain threshold
* ... where that threshold has something to do with the font size
* auto-width adjustment is on

I should point out that in all cases, the preview looks correct - only the exported image is sometimes broken.

For comparison I tested in Firefox (69.0) and all scenarios render correctly.

**Comment by oliversturm** [comment] 2019-09-11 15:20
Small addition: using [this URL](https://carbon.now.sh/?bg=rgba(255%2C255%2C255%2C0)&t=monokai&wt=none&l=graphql&ds=true&dsyoff=0px&dsblur=20px&wc=true&wa=true&pv=20px&ph=20px&ln=false&fl=1&fm=Fira%20Code&fs=12.5px&lh=133%25&si=false&es=2x&wm=false&code=type%2520Country%2520%257B%250A%2520%2520name%253A%2520String!%250A%2520%2520areaKM2%253A%2520Int!%250A%2520%2520population%253A%2520Int!%250A%2520%2520areaPerPerson%253A%2520Float!%250A%257D%250A%250Atype%2520Query%2520%257B%250A%2520%2520countries(searchNames%253A%2520%255BString!%255D)%253A%2520%255BCountry!%255D!%250A%257D), the issue can also be reproduced with Firefox 69.0 on Linux.

**Comment by mfix22** [comment] 2019-09-11 17:49
@oliversturm would you be able to push a PR that fixes the issue on `Firefox Linux`? It is working appropriately for `Firefox macOS`

**Comment by oliversturm** [comment] 2019-09-11 19:09
I have no idea at this time what the cause of the issue is. If I had to guess I would say that some kind of width calculation is very slightly off, so it renders incorrect results when certain combinations of fonts, font sizes and rendering engines are used.

**Comment by mfix22** [comment] 2019-09-12 01:48
@oliversturm are you able to reproduce it locally? If so, you can probably just add logic here: https://github.com/carbon-app/carbon/blob/master/components/Editor.js#L154 to add 1 or 2 pixels when the user-agent is Linux/Window & Firefox

**Comment by onelson** [comment] 2019-09-30 01:35
Noticing an incorrect linewrap of my own on Chrome 77.0.3865.90 (linux) with:

```rust
// Big Step Operational Semantics

impl Expression for Add {
    fn evaluate(&self, environment: &Environment) -> Expr {
        match (
            self.0.evaluate(environment).as_value(),
            self.1.evaluate(environment).as_value(),
        ) {
            (Some(Value::Number(a)), Some(Value::Number(b))) => Value::Number(a + b).into(),
            _ => panic!("Unexpected values"),
        }
    }
}
```


![png rendered output](https://user-images.githubusercontent.com/301388/65843590-4ab1cd80-e2e7-11e9-9f65-91c23bb17d55.png)

Seems like there should be a linebreak before the `_ => panic!("Unexpected values"),` instead of just following on as a continuation.

**Comment by rkoleci** [comment] 2021-12-06 13:07
Can you assign this to me ?

**Comment by mfix22** [comment] 2022-01-25 04:34
> Can you assign this to me ?

Done. Please just feel free to submit PRs to fix issues without claiming them in the issues themselves.

**Comment by mfix22** [comment] 2022-01-25 04:36
This is a duplicate of #743 (operating system specific overlay bug). Please continue the conversation on that thread. Thanks everyone for this discussion!

**Closed by mfix22** 2022-01-25 04:36 UTC
Labels: help wanted
