### ISSUE TITLE
Newlines in url stopped working

### ISSUE THREAD

**Issue by max-arnold** [carbon-app/carbon#929] opened 2020-01-10 10:00 UTC
The following yaml snippet isn't rendered properly

```
abc:
  - line1
  - line2
```

after being converted to url 

```
https://carbon.now.sh/?code=abc%3A%0A%20%20-%20line1%0A%20%20-%20line2%0A
```

<img width="807" alt="2020-01-10 at 16 58" src="https://user-images.githubusercontent.com/370942/72144041-65a5da80-33ca-11ea-8541-77d1588805a6.png">

Everything after the first `%0A` character is discarded.  This breaks editor integrations.

**Comment by mfix22** [comment] 2020-01-11 02:14
@max-arnold can you please dig deeper into what you mean? 
I did the following:
1. Pasted:
```
abc:
  - line1
  - line2
```
into Carbon
2. Copied the new URL that was generated
3. Opened a new tab with the just copied URL
4. And confirmed that it was rendered appropriately. 

Which part of this is "broken" to you?

**Comment by max-arnold** [comment] 2020-01-11 02:59
The broken part for me is the editor integration (https://github.com/veelenga/carbon-now-sh.el) which suddenly stopped working. I strongly believe that the integration itself is fine for two reasons:

1. I haven't changed anything in Emacs
2. Older carbon.now.sh urls that I found in my browser history also stopped working

The key to reproduce is not to paste manually anything into Carbon, but instead open the `https://carbon.now.sh/?code=` with urlencoded code.

An example of broken url: `https://carbon.now.sh/?code=abc%3A%0A%20%20-%20line1%0A%20%20-%20line2%0A`

**Comment by max-arnold** [comment] 2020-01-11 03:35
Version 4.3.14 doesn't have this problem

**Comment by mfix22** [comment] 2020-01-13 00:27
I think this was broken by https://github.com/zeit/next.js/pull/9638/files. 

CC'ing @timneutkens in case other apps are affected by this change. 

I am holding the `next` dependency at `9.1.4` until I can investigate further

**Comment by mfix22** [comment] 2020-01-13 00:42
@max-arnold does version [`4.3.16`](https://github.com/carbon-app/carbon/releases/tag/4.3.16) (https://carbon-7z357teu2.now.sh) solve the issue for you?

**Comment by max-arnold** [comment] 2020-01-13 08:16
@mfix22 4.3.16 works for me. Thank you Michael!

**Comment by mfix22** [comment] 2020-01-14 06:03
@max-arnold I am going to keep this open until we either fix it on our end, or it is solved here: https://github.com/zeit/next.js/issues/10066

**Comment by mfix22** [comment] 2020-01-14 06:04
@timer potentially this can be fixed on our end, but I wanted to tag you in case it was a regression.

**Comment by Timer** [comment] 2020-01-14 13:36
Yup, I plan on investigating soon to figure out the correct/intended behavior.

**Comment by Timer** [comment] 2020-01-15 03:59
Confirmed bug: https://github.com/GoogleChromeLabs/native-url/issues/14

**Comment by mfix22** [comment] 2020-01-16 05:40
@Timer thanks so much for investigating. Will follow along there.

**Closed** 2020-01-23 02:05 UTC
