### ISSUE TITLE
Code Snippets are gone!

### ISSUE THREAD

**Issue by Edudjr** [carbon-app/carbon#1334] opened 2022-02-07 03:24 UTC
**Describe the bug**
Today I checked [my Medium article](https://medium.com/geekculture/guide-to-prototype-pattern-in-swift-c6f4735d8e2b) which has many references to my Carbon snippets and they are all gone! Checking the "snippets" section on my account, I also cannot see anything.

**To Reproduce**

1. Login to account
2. Access Snippets

**Expected behavior**
Snippets should appear in both article and in my account

**Screenshots**
![Screenshot 2022-02-07 at 04 19 28](https://user-images.githubusercontent.com/6642478/152719328-03dbdc76-7f28-4d28-b577-3ef7a1d5b29c.png)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: MacOS 11.6
- Browser [e.g. Chrome, Safari, Firefox]: Opera
- Carbon URL [e.g. carbon.now.sh?bg=pink]: https://carbon.now.sh/embed/wjhyBwLy9vQrZ0B7yWnb?referrer=https%3A%2F%2Fmedium.com%2Fgeekculture%2Fguide-to-prototype-pattern-in-swift-c6f4735d8e2b

**Comment by DataSolveProblems** [comment] 2022-02-07 04:09
Having the same issue; code snippet is stuck on the loading page and all my embedded code snippets are gone. 

PS: Still patiently waiting for the premium service to be released.

**Comment by mfix22** [comment] 2022-02-08 00:56
Duplicate of #1327. We have reached Firebase platform limits (with zero warning or notice) and are trying to get our access restored. We appreciate your patience and understanding.

**Closed by mfix22** 2022-02-08 00:56 UTC
Labels: bug
