### ISSUE TITLE
Long line of code mixes up with next line when exporting PNG

### ISSUE THREAD

**Issue by BradleyHo** [carbon-app/carbon#951] opened 2020-02-27 06:41 UTC
### Expected Behavior
![carbon](https://user-images.githubusercontent.com/29351052/75418684-eec89080-58e8-11ea-8b19-33f82df27b17.png)
When a code line is too long, the previous line merges with the next line which makes it look odd.

### Actual Behavior

<details>
  <summary>Browser: </summary>
  
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  
</details>

**Comment by mfix22** [comment] 2020-02-27 07:18
@BradleyHo which operating system / browser did you create this image on?

**Comment by BradleyHo** [comment] 2020-02-27 07:19
Windows 10 running on Microsoft Edge (Chromium) stable.

**Comment by mfix22** [comment] 2020-02-29 02:38
Understood, and I apologize for this issue. We are already tracking this Windows measurement issuing in this thread: https://github.com/carbon-app/carbon/issues/781

Closing as duplicate of #781

**Closed** 2020-03-02 02:39 UTC
Labels: duplicate
