### ISSUE TITLE
The export picture is not complete.

### ISSUE THREAD

**Issue by Galaxy955** [carbon-app/carbon#1407] opened 2022-09-04 11:59 UTC
**Describe the bug**
The bug will appear when exporting png and svg. If you choose to export 2x and 4x scale, the exported picture
 is not complete, like this:
![carbon](https://user-images.githubusercontent.com/31366757/188312086-dd816ab5-d559-49aa-899e-519cb31d6cc1.png)

**To Reproduce**

1. Go to 'https://carbon.now.sh'
2. Click on 'Export', choose '2x' or '4x' and click the 'Download'
3. See error

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS 12.5.1
- Browser [e.g. Chrome, Safari, Firefox]: Safari
- Carbon URL [e.g. carbon.now.sh?bg=pink]: carbon.now.sh

**Comment by OkeyDev** [comment] 2022-09-10 07:18
Same issue at #1351. You can find patch here: #1405

**Comment by mfix22** [comment] 2022-11-07 01:12
Duplicate of #1351—I'll deploy the patch soon.

**Closed by mfix22** 2022-11-07 01:12 UTC
Labels: bug
